server:
  port: 18010
eureka:
  client:
    serviceUrl:
      defaultZoon: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://47.110.93.6:3306/wx_gzh?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
ribbon:
  eureka:
    enabled: true