server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    serviceUrl:
      defaultZoon: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
